---

- name: install Ubuntu prereqs
  apt: name="{{ item }}" update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - "apt-transport-https"

- name: packagecloud stanchion apt key
  apt_key: url="https://packagecloud.io/basho/stanchion/gpgkey"
  tags:
    - riak-install

- name: packagecloud stanchion apt_repo
  apt_repository: repo="deb https://packagecloud.io/basho/stanchion/ubuntu/ {{ ansible_distribution_release }} main"
  tags:
    - stanchion-install

- name: packagecloud stanchion apt_repo src
  apt_repository: repo="deb-src https://packagecloud.io/basho/stanchion/ubuntu/ {{ ansible_distribution_release }} main"
  tags:
    - stanchion-install

- name: install stanchion
  apt: name=stanchion update_cache=yes
  tags:
    - stanchion-install
