---

riakkv_protocol_buffers_port: "8087"
riakkv_host_address: "{{ ansible_default_ipv4.address }}"

riakcs_version: "2.1.1"
riakcs_listener_address: "{{ ansible_default_ipv4.address }}"
riakcs_listener_port: "8080"

stanchion_listener_address: "{{ ansible_default_ipv4.address }}"
stanchion_listener_port: "8085"
